baseURL = 'http://wiegandfamily.com/'
languageCode = 'en-us'
theme = "lynx-gohugo-theme"
title = "Chris Wiegand's site"
disableKinds = ["taxonomy", "term"]

[params]
  author = "Chris Wiegand"
  description = "Chris' personal musings."
  keywords = "blog,personal"

[author]
  name = "Chris Wiegand"
  headline = "My personal musings and things important to me"
  image = "https://avatars.githubusercontent.com/u/121301?s=400&v=4"
  homepage_links = [
    { link = { href = "https://www.wiegandfd.com/", text = "Wiegand Family Distribution can be found here", icon = "fa fa-beer" } },
    { twitter = "https://twitter.com/cdwiegand" },
    { github = "https://github.com/cdwiegand" },
    { mastodon = "https://mastodon.social/@chris_wiegand" },
    { tiktok = "https://www.tiktok.com/@the_tik_of_the_tok" },
    { youtube = "https://www.youtube.com/channel/UC5lxbRAQWAkaBYrTzKWTt1w" },
    { link = { href = "https://content-security-policy.com/", text = "Make sure your websites use CSP when possible", icon = "fa fa-lock" } }, 
    { link = { href = "https://securityheaders.io/?q=https%3A%2F%2Fwiegandfamily.com&followRedirects=on", text = "SecurityHeaders.io", icon = "fa fa-lock" } },
    { link = { href = "https://www.ssllabs.com/ssltest/analyze.html?d=wiegandfamily.com&hideResults=on", text = "SSLLabs.com", icon = "fa fa-lock" } },
    { link = { href = "https://observatory.mozilla.org/analyze/wiegandfamily.com", text = "Mozilla Observatory", icon = "fa fa-search" } },
    { link = { href = "#", text = "FCC Callsign: KV0LTZ", icon = "fa fa-wifi" } },
    { link = { href = "/public.key.2021.asc", text = "My primary GnuPG key (A3078AA1)", icon = "fa fa-key" } },
    { link = { href = "http://www.denverboyscouts.org/", text = "I donate much of my free time to Boy Scouts", icon = "fa fa-tree" } },
    { link = { href = "http://www.woodbadge.org/", text = "My Woodbadge critter: Fox", icon = "fa fa-ticket" } },
    { link = { href = "https://beafreemason.org/", text = "Be a Freemason", icon = "fa fa-handshake-o" } },
  ]

[markup.goldmark.renderer]
  unsafe = true

