window.wiegand_page_links = [
  {
    href: "https://www.wiegandfd.com/",
    text: "Wiegand Family Distribution can be found here",
    icon: "fa fa-beer",
    bgcolor: "bg-purple",
  },
  {
    href: "https://native-land.ca/",
    text: "I recognize I live on the traditional territories of the Arapaho, Ute, and Cheyenne nations.",
    icon: "fa fa-location-dot",
    bgcolor: "bg-white",
  },
  {
    href: "https://aurora156.org/",
    text: "Aurora Revelation Lodge 156",
    icon: "fa fa-compass-drafting",
    bgcolor: "bg-techelet",
  },
  {
    href: "https://project529.com/garage",
    text: "Register your bike BEFORE it's stolen",
    icon: "fa fa-bicycle",
    bgcolor: "bg-bikes",
  },
  { href: "https://strongtowns.org/", text: "Strong Towns", icon: "fa fa-house" },
  { href: "https://street-plans/", text: "Street Plans", icon: "fa fa-road" },
  { href: "https://bicyclecolorado.org/", text: "Bicycle Colorado", icon: "fa fa-bicycle" },
  { href: "https://bikeleague.org/", text: "Bike League", icon: "fa fa-bicycle" },
  { href: "https://nextcity.org/", text: "Building Better Cities", icon: "fa fa-city" },
  { href: "https://parkingreform.org/", text: "Parking Reform Network", icon: "fa fa-car" },
  { href: "https://incrementaldevelopment.org/", text: "Incremental Dev Alliance", icon: "fa fa-city" },
  { href: "https://www.betterblock.org/", text: "Better Block | Placemaking", icon: "fa fa-city" },
  { href: "https://bikelaneuprising.com/", text: "Bike Lane Uprising", icon: "fa fa-bicycle" },
  { href: "https://betterblock.org/", text: "Better Block", icon: "fa fa-city" },
  { href: "https://urbanistsociety.com/", text: "Urbanist Society", icon: "fa fa-city" },
  { href: "https://theurbanist.org/", text: "The Urbanist", icon: "fa fa-city" },
  { href: "https://neweracolorado.org/", text: "New Era Colorado", icon: "fa fa-city" },
  { href: "https://www.greaterdenvertransit.com/", text: "Greater Denver Transit", icon: "fa fa-bus" },
  { href: "https://twitter.com/cdwiegand", text: "Twitter", bgcolor: "link-twitter", icon: "fa fa-brands fa-twitter" },
  { href: "https://github.com/cdwiegand", text: "GitHub", bgcolor: "link-github", icon: "fa fa-brands fa-github" },
  {
    href: "https://mastodon.social/@chris_wiegand",
    text: "Mastodon",
    bgcolor: "link-mastodon",
    icon: "fa fa-brands fa-mastodon",
  },
  {
    href: "https://www.tiktok.com/@the_tik_of_the_tok",
    text: "TikTok",
    bgcolor: "link-tiktok",
    icon: "fa fa-brands fa-tiktok",
  },
  {
    href: "https://www.youtube.com/channel/UC5lxbRAQWAkaBYrTzKWTt1w",
    text: "Youtube",
    bgcolor: "link-youtube",
    icon: "fa fa-brands fa-youtube",
  },
  {
    href: "https://content-security-policy.com/",
    text: "Make sure your websites use CSP when possible",
    icon: "fa fa-lock",
  },
  {
    href: "https://securityheaders.io/?q=https%3A%2F%2Fwiegandfamily.com&followRedirects=on",
    text: "SecurityHeaders.io",
    icon: "fa fa-lock",
  },
  {
    href: "https://www.ssllabs.com/ssltest/analyze.html?d=wiegandfamily.com&hideResults=on",
    text: "SSLLabs.com",
    icon: "fa fa-lock",
  },
  {
    href: "https://observatory.mozilla.org/analyze/wiegandfamily.com",
    text: "Mozilla Observatory",
    icon: "fa fa-search",
    bgcolor: "bg-purple",
  },
  { href: "#", text: "FCC Callsign: KV0LTZ", icon: "fa fa-wifi", bgcolor: "bg-purple" },
  { href: "/public.key.2021.asc", text: "My primary GnuPG key (A3078AA1)", icon: "fa fa-key" },
  { href: "http://www.woodbadge.org/", text: "My Woodbadge critter: Fox", icon: "fa fa-ticket" },
];
